title: Raman Karp # your name (or website title) here
logo: "/images/Image (2).jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my portfolio page! Based in NYC, I am passionate about solving problems and deriving insights from data. My tools: PostgreSQL,Power BI, Excel, ChatGPT. I hold a BA in Economics from the City University of New York. Enjoy browsing through the content, and feel free to contact me via LinkedIn!
  <br> <br>
  <a href="https://www.linkedin.com/in/raman-karp-a13436b8/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-E2W67JF873 # your Google Analytics tracking ID here
