title: Raman K. # your name (or website title) here
logo: "/images/IMG_9236.PNG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my portfolio page! Solving problems with data and getting insights out of data is something that I really like. My 
  tools: SQL (Pg Agmin), Power Bi, Excell, Chat GPT. Holds an BA  in Economics from City University of New York. Have fun in 
  browsing through the content! And feel free to contact me via LinkedIn.
  <br> <br>
  <a href="https://www.linkedin.com/in/raman-karp-a13436b8/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
